---
domamin: ""
garden: ""
hosted_zone_id: ""
aws_region: ""

ci_subdomain: "ci"
status_subdomain: "status"

letsencrypt_ca: "https://acme-v01.api.letsencrypt.org/directory"

bastion_is_master: yes
bastion_master_ip: ""
bastion_master_ready: no
bastion_services_username: bastion
bastion_services_password: bastion

jenkins_admin_username: "{{ bastion_services_username }}"
jenkins_admin_password: "{{ bastion_services_password }}"
jenkins_plugins:
  - extended-choice-parameter
  - extensible-choice-parameter
  - simple-theme-plugin
  - role-strategy
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

traefik_status_port: 9000
traefik_ci_port: 8080
traefik_status_username: "{{ bastion_services_username }}"
traefik_status_password: "{{ bastion_services_password }}"

efs_mount_target: ""

garden_s3_bucket_primary: ""
garden_s3_bucket_backups: ""
