language: node_js
node_js:
  - "7"

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

install:
  - npm install

script:
  - npm test