---
- name: Encrypt the admin user password
  command: >
    python -c 'import bcrypt; print(bcrypt.hashpw("{{ jenkins_admin_password }}", bcrypt.gensalt(prefix=b"2a")))'
  register: jenkins_admin_password_bcrypt
  changed_when: false

- name: See if our admin user already exists
  stat:
    path: /var/lib/jenkins/users/{{ jenkins_admin_username }}
  register: admin_user_dir
  changed_when: false

- name: Copy default admin record to our new user record
  command: >
    cp -r /var/lib/jenkins/users/admin /var/lib/jenkins/users/{{ jenkins_admin_username }}
  when: not admin_user_dir.stat.exists
  notify: restart jenkins

- name: Set our admin user password
  lineinfile:
    dest: /var/lib/jenkins/users/{{ jenkins_admin_username }}/config.xml
    regexp: '^(\s+)?<passwordHash>.*<\/passwordHash>$'
    line: "      <passwordHash>#jbcrypt:{{ jenkins_admin_password_bcrypt.stdout }}</passwordHash>"
  notify: restart jenkins

- name: Set our new users fullName
  lineinfile:
    dest: /var/lib/jenkins/users/{{ jenkins_admin_username }}/config.xml
    regexp: '^(\s+)?<fullName>.*<\/fullName>$'
    line: "  <fullName>{{ jenkins_admin_username }}</fullName>"
  notify: restart jenkins

- meta: flush_handlers

- name: Make sure Jenkins is running before continuing
  shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    with_dependencies: yes
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins