---
- name: Modify variables in init file
  lineinfile:
    dest: /etc/default/jenkins
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option}}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
  with_items:
      "{{ jenkins_init_changes }}"
  register: jenkins_init_config

- name: Set the Jenkins home directory
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME=/var/lib/jenkins'
  register: jenkins_home_config

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: 'HTTP_PORT=8080'
  register: jenkins_http_config

- name: Immediately restart Jenkins on http or user changes.
  service: name=jenkins state=restarted
  when: (jenkins_init_config is defined and jenkins_init_config.changed) or
        (jenkins_http_config is defined and jenkins_http_config.changed) or
        (jenkins_home_config is defined and jenkins_home_config.changed)
