---

- name: Make sure certs directory exists
  file:
    path: /etc/ssl/certs
    state: directory

- name: Get ssl certs from the CA server
  command: >
    rsync -avz --rsync-path="sudo rsync" -e "ssh -i /home/ubuntu/.ssh/ca_rsa -o StrictHostKeyChecking=no" ubuntu@{{ ca_ip }}:/srv/dehydrated/certs/ /etc/ssl/certs/

- name: Add cron job to sync with certs from the CA server every month
  cron:
    job: 'rsync --rsync-path="sudo rsync" -avz -e "ssh -i /home/ubuntu/.ssh/ca_rsa -o StrictHostKeyChecking=no" ubuntu@{{ ca_ip }}:/srv/dehydrated/certs/ /etc/ssl/certs/'
    day: 1
    hour: 2
    minute: 0