version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/cloud-gardens
    steps:
      - checkout
      - run:
          name: download-terraform
          command: 'curl -fSL "https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip" -o terraform.zip'
      - run:
          name: unzip-terraform
          command: 'sudo unzip terraform.zip -d /opt/terraform'
      - run:
          name: install-terraform
          command: 'sudo ln -s /opt/terraform/terraform /usr/bin/terraform'
      - run:
          name: remove-terraform-download
          command: 'rm -f terraform.zip'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-local
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test