version: 2
jobs:
  build:
    working_directory: ~/cloud-gardens
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: download-terraform
          command: 'curl -fSL "https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip" -o terraform.zip'
      - run:
          name: unzip-terraform
          command: 'sudo unzip terraform.zip -d /opt/terraform'
      - run:
          name: install-terraform
          command: 'sudo ln -s /opt/terraform/terraform /usr/bin/terraform'
      - run:
          name: remove-terraform-download
          command: 'rm -f terraform.zip'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-local
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml