---
domain: ""
ci_subdomain: ""
status_subdomain: ""

letsencrypt_enabled: yes
letsencrypt_ca: "https://acme-v01.api.letsencrypt.org/directory"

aws_access_key_id: ""
aws_secret_access_key: ""

traefik_version: "v1.2.3"
traefik_status_username: "admin"
traefik_status_password: "admin"
traefik_status_port: 9000
traefik_ci_port: 8080
traefik_install_dir: /opt/traefik
traefik_binary_url: "https://github.com/containous/traefik/releases/download/{{ traefik_version }}/traefik_linux-amd64"
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_file: /etc/traefik.toml
traefik_template: traefik.toml
traefik_systemd_unit_template: traefik.service
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_debug: "false"
traefik_log_level: "INFO"
traefik_logs_directory: /var/log/traefik
traefik_ecs_cluster_name: "default"
traefik_ecs_region: "us-east-1"
