---

- name: Get the hashed status user password
  shell: >
    currenthash=$(cat /etc/traefik.toml | grep -e "^users" | awk -F '"' '{print $2}' | awk -F ':' '{print $2}') && /usr/local/bin/print-password-hash.py "${currenthash}" "{{ traefik_status_password }}"
  register: traefik_status_password_bcrypt
  changed_when: false

- name: Create traefik systemd unit
  template:
    src: "{{ traefik_systemd_unit_template }}.j2"
    dest: "{{ traefik_systemd_unit_dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd daemon
    - restart traefik

- name: Ensure install & config directory exists
  file:
    path: "{{ traefik_install_dir }}"
    state: directory

- name: Ensure traefik logs directory exists
  file:
    path: "{{ traefik_logs_directory }}"
    state: directory

- name: Download Traefik binary
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_bin_path }}"

- name: Copy traefik config file
  template:
    src: "{{ traefik_template }}.j2"
    dest: "{{ traefik_config_file }}"
    owner: root
    group: root
    mode: 0744
  notify:
    - restart traefik

- name: Ensure traefik service is enabled and running
  service:
    name: traefik
    state: started
    enabled: yes