---

- set_fact:
    __ssl_certs_rsync_command: 'rsync -avz --rsync-path="sudo rsync" -e "ssh -i /home/ubuntu/.ssh/bastion_rsa -o StrictHostKeyChecking=no" ubuntu@{{ ssl_certs_master_ip }}:/etc/ssl/certs/ /etc/ssl/certs/'

- name: Get ssl certs from master
  shell: >
    {{ __ssl_certs_rsync_command }}

- name: Add/update cron job to sync with certs from master every month
  cron:
    job: "{{ __ssl_certs_rsync_command }}"
    day: 1
    hour: 2
    minute: 0