---
- name: Provision Bastion Server
  hosts: all
  become: yes

  pre_tasks:
    - name: Include bastion variables
      include_vars:
        dir: vars/bastion
      tags: [ always ]

    - name: Include override variables
      include_vars:
        dir: vars/overrides
        ignore_files: ['.keep']
      tags: [ always ]

  roles:
    - role: aws
      tags: [ jenkins, aws ]
    - role: bcrypt
      tags: [ bcrypt ]
    - role: letsencrypt
      ssl_certs_is_master: "{{ bastion_is_master }}"
      ssl_certs_master_ip: "{{ bastion_master_ip }}"
      ssl_certs_master_ready: "{{ bastion_master_ready }}"
      letsencrypt_domains: ["{{ domain }}","{{ traefik_ci_subdomain }}.{{ domain }}","{{ traefik_status_subdomain }}.{{ domain }}"]
      tags: [ ssl ]
    - role: geerlingguy.jenkins
      jenkins_plugins: []
      tags: [ jenkins ]
    - role: jenkins
      tags: [ jenkins ]
    - role: aws
      aws_config_directories: [ { path: /var/lib/jenkins/.aws, owner: jenkins } ]
      tags: [ aws, jenkins ]
    - role: traefik
      traefik_hostname: "{{ domain }}"
      when: bastion_master_ready
      tags: [ ssl, traefik ]
    - role: logrotate
      tags: [ logrotate ]

  tasks:
    - include: "{{ playbook_dir }}/.custom/bastion.yml"
      tags: [ custom ]
