---
- name: Provision Bastion Server
  hosts: all
  become: yes

  pre_tasks:
    - name: Include bastion variables
      include_vars:
        dir: vars/bastion

    - name: Include override variables
      include_vars:
        dir: vars/overrides
        ignore_files: ['.keep']

  roles:
    - { role: aws }
    - { role: bcrypt }
    - { role: ca-sync }
    - { role: geerlingguy.jenkins, jenkins_plugins: [] }
    - { role: jenkins,  }
    - { role: aws, aws_config_directories: [ { path: /var/lib/jenkins/.aws, owner: jenkins } ] }
    - { role: traefik, traefik_hostname: "{{ domain }}" }
    - { role: logrotate }

  tasks:
    - include: "{{ playbook_dir }}/.custom/bastion.yml"
