---
- name: Provision Certificate Authority Server
  hosts: all
  become: yes

  pre_tasks:

    - name: Include override variables
      include_vars:
        dir: vars/overrides
        ignore_files: ['.keep']

  roles:
    - { role: aws }
    - { role: letsencrypt, letsencrypt_domains: ["{{ domain }}","{{ traefik_ci_subdomain }}.{{ domain }}","{{ traefik_status_subdomain }}.{{ domain }}"] }
